# Generated by Django 5.2.11 on 2026-02-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
