# Generated by Django 5.2.11 on 2026-03-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
